-- MySQL Script generated by MySQL Workbench
-- Mon Nov 23 17:28:02 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema resto
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema resto
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `resto` DEFAULT CHARACTER SET utf8 ;
USE `resto` ;

-- -----------------------------------------------------
-- Table `resto`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `resto`.`user` (
  `iduser` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `prenome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`iduser`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `resto`.`plat`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `resto`.`plat` (
  `idplat` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nomePlat` VARCHAR(45) NOT NULL,
  `descPlat` VARCHAR(45) NOT NULL,
  `prixPlat` INT NOT NULL,
  `imgPlat` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idplat`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `resto`.`command`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `resto`.`command` (
  `idcommand` INT NOT NULL AUTO_INCREMENT,
  `dateCommand` DATE NOT NULL,
  `plat_idplat` INT UNSIGNED NOT NULL,
  `user_iduser` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`idcommand`, `plat_idplat`, `user_iduser`),
  UNIQUE INDEX `idcommand_UNIQUE` (`idcommand` ASC) VISIBLE,
  INDEX `fk_command_plat_idx` (`plat_idplat` ASC) VISIBLE,
  INDEX `fk_command_user1_idx` (`user_iduser` ASC) VISIBLE,
  CONSTRAINT `fk_command_plat`
    FOREIGN KEY (`plat_idplat`)
    REFERENCES `resto`.`plat` (`idplat`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_command_user1`
    FOREIGN KEY (`user_iduser`)
    REFERENCES `resto`.`user` (`iduser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
